### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by jacekmigacz** [inukshuk/sqleton#9]
I was trying with fedora container image:
```
[root@6752916c1e61 /]# /node_modules/sqleton/bin/sqleton -o /tmp/test.svg  /tmp/p3WLCPRa/test.db
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn fdp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn fdp',
  path: 'fdp',
  spawnargs: [ '-Tsvg', '-o/tmp/test.svg' ]
}
```

**Comment by inukshuk** [comment]
You need to install the graphviz package or make sure the `fdp` binary is in your path.

**Comment by vjohansen** [comment]
I had the same issue.  

After installing graphviz on Windows I **only** have dot.exe so only -L dot works

**Comment by inukshuk** [comment]
@vjohansen thanks!

**Comment by vjohansen** [comment]
Also if I use sqleton to create .dot  files then I can use dot.exe on these and set the layout method via -K. 

For example  _dot -Kneato_ ...  or 

    dot -Kfdp  -Tpng -odb.png db.dot
